apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-grpc-service
  description: "test-grpc-service"
  tags:
    - java
    - grpc
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: spotify-portal-public-demo/test-grpc-service
    sonarqube.org/project-key: spotify-portal-public-demo_test-grpc-service
    grafana/dashboard-selector: test-grpc-service
    backstage.io/kubernetes-id: test-grpc-service
    backstage.io/kubernetes-namespace: test-grpc-service
    backstage.io/kubernetes-label-selector: app=test-grpc-service
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/devex"
