name: Review build

on:
  pull_request:
    branches: ["main"]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "corretto"
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
